name: apron_icons
description: Collection of beautiful and well-designed icons from Cookpad Apron UI Kit
version: 0.0.1
homepage: https://github.com/hanmajid/apron_icons
issue_tracker: https://github.com/hanmajid/apron_icons/issues
repository: https://github.com/hanmajid/apron_icons
funding:
  - https://github.com/sponsors/hanmajid

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  fonts:
    - family: ApronIcons
      fonts:
        - asset: assets/ApronIcons.ttf

topics:
  - assets
  - icons
  - ui

screenshots:
  - description: 'Cookpad Apron icons'
    path: apron-icons.png