// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing Apron icons.
///
/// This font was generated by FlutterIcon.com.
class ApronIcons {
  /// No need for constructor. All properties are static.
  ApronIcons._();

  /// Apron icons family name.
  static const _kFontFam = 'ApronIcons';

  /// Apron icons package name.
  static const String? _kFontPkg = 'apron_icons';

  /// Icon data for 'arrow_down' glyph.
  static const IconData arrow_down =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_down_1' glyph.
  static const IconData arrow_down_1 =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bell' glyph.
  static const IconData bell =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bell_1' glyph.
  static const IconData bell_1 =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bento_1' glyph.
  static const IconData bento_1 =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'blank_link_1' glyph.
  static const IconData blank_link_1 =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bread' glyph.
  static const IconData bread =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bookmark' glyph.
  static const IconData bookmark =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bento' glyph.
  static const IconData bento =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar' glyph.
  static const IconData calendar =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar_1' glyph.
  static const IconData calendar_1 =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bread_1' glyph.
  static const IconData bread_1 =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'blank_link' glyph.
  static const IconData blank_link =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bookmark_1' glyph.
  static const IconData bookmark_1 =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chicken_1' glyph.
  static const IconData chicken_1 =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chef_man' glyph.
  static const IconData chef_man =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chicken' glyph.
  static const IconData chicken =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cookwear_1' glyph.
  static const IconData cookwear_1 =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cookwear' glyph.
  static const IconData cookwear =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'coolbag' glyph.
  static const IconData coolbag =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'coolbag_1' glyph.
  static const IconData coolbag_1 =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'crop' glyph.
  static const IconData crop =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chef_man_1' glyph.
  static const IconData chef_man_1 =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dishsoap_1' glyph.
  static const IconData dishsoap_1 =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'diet' glyph.
  static const IconData diet =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'crop_1' glyph.
  static const IconData crop_1 =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dishsoap' glyph.
  static const IconData dishsoap =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'diet_1' glyph.
  static const IconData diet_1 =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'earth_ap_1' glyph.
  static const IconData earth_ap_1 =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'driedfish_1' glyph.
  static const IconData driedfish_1 =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'driedfish' glyph.
  static const IconData driedfish =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'edit' glyph.
  static const IconData edit =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'earth_ap' glyph.
  static const IconData earth_ap =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'flourbag' glyph.
  static const IconData flourbag =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'flourbag_1' glyph.
  static const IconData flourbag_1 =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'girl' glyph.
  static const IconData girl =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'healthy' glyph.
  static const IconData healthy =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'healthy_1' glyph.
  static const IconData healthy_1 =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'edit_1' glyph.
  static const IconData edit_1 =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart_1' glyph.
  static const IconData heart_1 =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart' glyph.
  static const IconData heart =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'girl_1' glyph.
  static const IconData girl_1 =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'home_1' glyph.
  static const IconData home_1 =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'human' glyph.
  static const IconData human =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'home' glyph.
  static const IconData home =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'kaimono' glyph.
  static const IconData kaimono =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image_1' glyph.
  static const IconData image_1 =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'kitchen' glyph.
  static const IconData kitchen =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image' glyph.
  static const IconData image =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'kondate' glyph.
  static const IconData kondate =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'kitchen_1' glyph.
  static const IconData kitchen_1 =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'kondate_1' glyph.
  static const IconData kondate_1 =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'human_1' glyph.
  static const IconData human_1 =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list_1' glyph.
  static const IconData list_1 =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'music' glyph.
  static const IconData music =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock' glyph.
  static const IconData lock =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list' glyph.
  static const IconData list =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'music_1' glyph.
  static const IconData music_1 =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'myfolder_add_1' glyph.
  static const IconData myfolder_add_1 =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_1' glyph.
  static const IconData lock_1 =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'oden_1' glyph.
  static const IconData oden_1 =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'oden' glyph.
  static const IconData oden =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mic' glyph.
  static const IconData mic =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'kaimono_1' glyph.
  static const IconData kaimono_1 =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'onion' glyph.
  static const IconData onion =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'onion_1' glyph.
  static const IconData onion_1 =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'push_pin' glyph.
  static const IconData push_pin =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'print' glyph.
  static const IconData print =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'print_1' glyph.
  static const IconData print_1 =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'push_pin_1' glyph.
  static const IconData push_pin_1 =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'myfolder_add' glyph.
  static const IconData myfolder_add =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'meat' glyph.
  static const IconData meat =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rice_1' glyph.
  static const IconData rice_1 =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'meat_1' glyph.
  static const IconData meat_1 =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sausage_1' glyph.
  static const IconData sausage_1 =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mic_1' glyph.
  static const IconData mic_1 =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'setting' glyph.
  static const IconData setting =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shrimp' glyph.
  static const IconData shrimp =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sidedish' glyph.
  static const IconData sidedish =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rank' glyph.
  static const IconData rank =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shrimp_1' glyph.
  static const IconData shrimp_1 =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sidedish_1' glyph.
  static const IconData sidedish_1 =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sake_1' glyph.
  static const IconData sake_1 =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sports_1' glyph.
  static const IconData sports_1 =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'setting_1' glyph.
  static const IconData setting_1 =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rice' glyph.
  static const IconData rice =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sausage' glyph.
  static const IconData sausage =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sports' glyph.
  static const IconData sports =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star_1' glyph.
  static const IconData star_1 =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rank_1' glyph.
  static const IconData rank_1 =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sake' glyph.
  static const IconData sake =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'trash_1' glyph.
  static const IconData trash_1 =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'trash' glyph.
  static const IconData trash =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star' glyph.
  static const IconData star =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user' glyph.
  static const IconData user =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'video' glyph.
  static const IconData video =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'video_1' glyph.
  static const IconData video_1 =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_1' glyph.
  static const IconData user_1 =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
